---
roles:
  - name: pki
    src: https://opendev.org/openstack/ansible-role-pki
    scm: git
    version: stable/2025.2
collections:
  - name: community.crypto
    source: https://github.com/ansible-collections/community.crypto
    type: git
  - name: ansible.utils
    source: https://github.com/ansible-collections/ansible.utils
    type: git
